---
- hosts: localhost
  gather_facts: True
  tasks:
  - name: creating ec2
    ec2:
      aws_access_key: AKIA3T4J3VKYSROOBOEQ 
      aws_secret_key: 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
      region: us-east-1
      key_name: eli_k8s     
      instance_type: t2.micro
      image: ami-0261755bbcb8c4a84
      wait: yes
      group: default
      count: 1
      vpc_subnet_id: subnet-018934fa4ce6e6bc5
      assign_public_ip: yes
